ESTIMATE_CURPAIR = 'EURUSD'
#  FEATURE_CURPAIRS = ['AUDJPY', 'AUDNZD', 'AUDUSD', 'CADJPY', 'CHFJPY',
                    #  'EURCHF', 'EURGBP', 'EURJPY', 'EURUSD', 'GBPJPY',
                    #  'GBPUSD', 'NZDUSD', 'USDCAD', 'USDCHF', 'USDJPY']
FEATURE_CURPAIRS = ['AUDUSD', 'EURCHF', 'EURGBP', 'EURJPY', 'EURUSD',
                    'GBPUSD', 'NZDUSD', 'USDCAD', 'USDCHF', 'USDJPY']
OUTPUT_FILE = 'output'
TIMESLOT_LEN = 1
WINDOW_SIZE = 3
